version: '3.8'

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: furniture
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/furniture
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    depends_on:
      - db
    ports:
      - "8080:8080"
    volumes:
      - uploads:/app/uploads

  frontend:
    build:
      context: ./frontend
    depends_on:
      - backend
    ports:
      - "80:80"

volumes:
  postgres-data:
  uploads:
