name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Build Backend
        run: |
          cd backend
          ./gradlew build --no-daemon

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Build Frontend
        run: |
          cd frontend
          npm install
          npm run build

      - name: Deploy to Render
        if: ${{ secrets.RENDER_DEPLOY_HOOK != '' }}
        run: curl -X POST "$RENDER_DEPLOY_HOOK"

      - name: Deploy to Heroku
        if: ${{ secrets.HEROKU_API_KEY != '' }}
        uses: akhileshns/heroku-deploy@v3.13.15
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
